//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.ServerASMX.Test.Tools.CustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notifier", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.CustomerUpdateCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.CustomerActivityStateCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.CustomerDeleteCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.CustomerAddCommand))]
    public partial class Notifier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerUpdateCommand", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerUpdateCommand : POC.ServerASMX.Test.Tools.CustomerService.Notifier {
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime BirthField;
        
        private POC.ServerASMX.Test.Tools.CustomerService.EGender GenderField;
        
        private decimal CashBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Birth {
            get {
                return this.BirthField;
            }
            set {
                if ((this.BirthField.Equals(value) != true)) {
                    this.BirthField = value;
                    this.RaisePropertyChanged("Birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public POC.ServerASMX.Test.Tools.CustomerService.EGender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal CashBalance {
            get {
                return this.CashBalanceField;
            }
            set {
                if ((this.CashBalanceField.Equals(value) != true)) {
                    this.CashBalanceField = value;
                    this.RaisePropertyChanged("CashBalance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerActivityStateCommand", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerActivityStateCommand : POC.ServerASMX.Test.Tools.CustomerService.Notifier {
        
        private long IdField;
        
        private bool ActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDeleteCommand", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerDeleteCommand : POC.ServerASMX.Test.Tools.CustomerService.Notifier {
        
        private long IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerAddCommand", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerAddCommand : POC.ServerASMX.Test.Tools.CustomerService.Notifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime BirthField;
        
        private POC.ServerASMX.Test.Tools.CustomerService.EGender GenderField;
        
        private decimal CashBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Birth {
            get {
                return this.BirthField;
            }
            set {
                if ((this.BirthField.Equals(value) != true)) {
                    this.BirthField = value;
                    this.RaisePropertyChanged("Birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public POC.ServerASMX.Test.Tools.CustomerService.EGender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal CashBalance {
            get {
                return this.CashBalanceField;
            }
            set {
                if ((this.CashBalanceField.Equals(value) != true)) {
                    this.CashBalanceField = value;
                    this.RaisePropertyChanged("CashBalance");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EGender", Namespace="http://tempuri.org/")]
    public enum EGender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.CustomerAddCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.Notifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.EGender))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<POC.ServerASMX.Test.Tools.CustomerService.Notification>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.Notification))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.CustomerCommandResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.CustomerUpdateCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.CustomerActivityStateCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.CustomerDeleteCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POC.ServerASMX.Test.Tools.CustomerService.CustomerQueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<POC.ServerASMX.Test.Tools.CustomerService.CustomerQueryResult>))]
    public partial class CommandResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<POC.ServerASMX.Test.Tools.CustomerService.Notification> ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<POC.ServerASMX.Test.Tools.CustomerService.Notification> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Notification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Property {
            get {
                return this.PropertyField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyField, value) != true)) {
                    this.PropertyField = value;
                    this.RaisePropertyChanged("Property");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerCommandResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerCommandResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime BirthField;
        
        private POC.ServerASMX.Test.Tools.CustomerService.EGender GenderField;
        
        private decimal CashBalanceField;
        
        private bool ActiveField;
        
        private System.DateTime CreationDateField;
        
        private System.Nullable<System.DateTime> ChangeDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Birth {
            get {
                return this.BirthField;
            }
            set {
                if ((this.BirthField.Equals(value) != true)) {
                    this.BirthField = value;
                    this.RaisePropertyChanged("Birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public POC.ServerASMX.Test.Tools.CustomerService.EGender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal CashBalance {
            get {
                return this.CashBalanceField;
            }
            set {
                if ((this.CashBalanceField.Equals(value) != true)) {
                    this.CashBalanceField = value;
                    this.RaisePropertyChanged("CashBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> ChangeDate {
            get {
                return this.ChangeDateField;
            }
            set {
                if ((this.ChangeDateField.Equals(value) != true)) {
                    this.ChangeDateField = value;
                    this.RaisePropertyChanged("ChangeDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerQueryResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerQueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime BirthField;
        
        private POC.ServerASMX.Test.Tools.CustomerService.EGender GenderField;
        
        private decimal CashBalanceField;
        
        private bool ActiveField;
        
        private System.DateTime CreationDateField;
        
        private System.Nullable<System.DateTime> ChangeDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Birth {
            get {
                return this.BirthField;
            }
            set {
                if ((this.BirthField.Equals(value) != true)) {
                    this.BirthField = value;
                    this.RaisePropertyChanged("Birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public POC.ServerASMX.Test.Tools.CustomerService.EGender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal CashBalance {
            get {
                return this.CashBalanceField;
            }
            set {
                if ((this.CashBalanceField.Equals(value) != true)) {
                    this.CashBalanceField = value;
                    this.RaisePropertyChanged("CashBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> ChangeDate {
            get {
                return this.ChangeDateField;
            }
            set {
                if ((this.ChangeDateField.Equals(value) != true)) {
                    this.ChangeDateField = value;
                    this.RaisePropertyChanged("ChangeDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.CustomerServiceSoap")]
    public interface CustomerServiceSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento command no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        POC.ServerASMX.Test.Tools.CustomerService.AddResponse Add(POC.ServerASMX.Test.Tools.CustomerService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.AddResponse> AddAsync(POC.ServerASMX.Test.Tools.CustomerService.AddRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento command no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        POC.ServerASMX.Test.Tools.CustomerService.UpdateResponse Update(POC.ServerASMX.Test.Tools.CustomerService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.UpdateResponse> UpdateAsync(POC.ServerASMX.Test.Tools.CustomerService.UpdateRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento command no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeActivityState", ReplyAction="*")]
        POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateResponse ChangeActivityState(POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeActivityState", ReplyAction="*")]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateResponse> ChangeActivityStateAsync(POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento command no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        POC.ServerASMX.Test.Tools.CustomerService.DeleteResponse Delete(POC.ServerASMX.Test.Tools.CustomerService.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.DeleteResponse> DeleteAsync(POC.ServerASMX.Test.Tools.CustomerService.DeleteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento GetResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        POC.ServerASMX.Test.Tools.CustomerService.GetResponse Get(POC.ServerASMX.Test.Tools.CustomerService.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.GetResponse> GetAsync(POC.ServerASMX.Test.Tools.CustomerService.GetRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento ListResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        POC.ServerASMX.Test.Tools.CustomerService.ListResponse List(POC.ServerASMX.Test.Tools.CustomerService.ListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.ListResponse> ListAsync(POC.ServerASMX.Test.Tools.CustomerService.ListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(POC.ServerASMX.Test.Tools.CustomerService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.CustomerAddCommand command;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(POC.ServerASMX.Test.Tools.CustomerService.CustomerAddCommand command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(POC.ServerASMX.Test.Tools.CustomerService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.CommandResult AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(POC.ServerASMX.Test.Tools.CustomerService.CommandResult AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(POC.ServerASMX.Test.Tools.CustomerService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.CustomerUpdateCommand command;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(POC.ServerASMX.Test.Tools.CustomerService.CustomerUpdateCommand command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(POC.ServerASMX.Test.Tools.CustomerService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.CommandResult UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(POC.ServerASMX.Test.Tools.CustomerService.CommandResult UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeActivityStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeActivityState", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequestBody Body;
        
        public ChangeActivityStateRequest() {
        }
        
        public ChangeActivityStateRequest(POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeActivityStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.CustomerActivityStateCommand command;
        
        public ChangeActivityStateRequestBody() {
        }
        
        public ChangeActivityStateRequestBody(POC.ServerASMX.Test.Tools.CustomerService.CustomerActivityStateCommand command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeActivityStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeActivityStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateResponseBody Body;
        
        public ChangeActivityStateResponse() {
        }
        
        public ChangeActivityStateResponse(POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeActivityStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.CommandResult ChangeActivityStateResult;
        
        public ChangeActivityStateResponseBody() {
        }
        
        public ChangeActivityStateResponseBody(POC.ServerASMX.Test.Tools.CustomerService.CommandResult ChangeActivityStateResult) {
            this.ChangeActivityStateResult = ChangeActivityStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(POC.ServerASMX.Test.Tools.CustomerService.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.CustomerDeleteCommand command;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(POC.ServerASMX.Test.Tools.CustomerService.CustomerDeleteCommand command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(POC.ServerASMX.Test.Tools.CustomerService.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.CommandResult DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(POC.ServerASMX.Test.Tools.CustomerService.CommandResult DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(POC.ServerASMX.Test.Tools.CustomerService.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(POC.ServerASMX.Test.Tools.CustomerService.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.CustomerQueryResult GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(POC.ServerASMX.Test.Tools.CustomerService.CustomerQueryResult GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="List", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.ListRequestBody Body;
        
        public ListRequest() {
        }
        
        public ListRequest(POC.ServerASMX.Test.Tools.CustomerService.ListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListRequestBody {
        
        public ListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListResponse", Namespace="http://tempuri.org/", Order=0)]
        public POC.ServerASMX.Test.Tools.CustomerService.ListResponseBody Body;
        
        public ListResponse() {
        }
        
        public ListResponse(POC.ServerASMX.Test.Tools.CustomerService.ListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<POC.ServerASMX.Test.Tools.CustomerService.CustomerQueryResult> ListResult;
        
        public ListResponseBody() {
        }
        
        public ListResponseBody(System.Collections.Generic.List<POC.ServerASMX.Test.Tools.CustomerService.CustomerQueryResult> ListResult) {
            this.ListResult = ListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceSoapChannel : POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceSoapClient : System.ServiceModel.ClientBase<POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap>, POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap {
        
        public CustomerServiceSoapClient() {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POC.ServerASMX.Test.Tools.CustomerService.AddResponse POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.Add(POC.ServerASMX.Test.Tools.CustomerService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public POC.ServerASMX.Test.Tools.CustomerService.CommandResult Add(POC.ServerASMX.Test.Tools.CustomerService.CustomerAddCommand command) {
            POC.ServerASMX.Test.Tools.CustomerService.AddRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.AddRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.AddRequestBody();
            inValue.Body.command = command;
            POC.ServerASMX.Test.Tools.CustomerService.AddResponse retVal = ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.AddResponse> POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.AddAsync(POC.ServerASMX.Test.Tools.CustomerService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.AddResponse> AddAsync(POC.ServerASMX.Test.Tools.CustomerService.CustomerAddCommand command) {
            POC.ServerASMX.Test.Tools.CustomerService.AddRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.AddRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.AddRequestBody();
            inValue.Body.command = command;
            return ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POC.ServerASMX.Test.Tools.CustomerService.UpdateResponse POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.Update(POC.ServerASMX.Test.Tools.CustomerService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public POC.ServerASMX.Test.Tools.CustomerService.CommandResult Update(POC.ServerASMX.Test.Tools.CustomerService.CustomerUpdateCommand command) {
            POC.ServerASMX.Test.Tools.CustomerService.UpdateRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.UpdateRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.UpdateRequestBody();
            inValue.Body.command = command;
            POC.ServerASMX.Test.Tools.CustomerService.UpdateResponse retVal = ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.UpdateResponse> POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.UpdateAsync(POC.ServerASMX.Test.Tools.CustomerService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.UpdateResponse> UpdateAsync(POC.ServerASMX.Test.Tools.CustomerService.CustomerUpdateCommand command) {
            POC.ServerASMX.Test.Tools.CustomerService.UpdateRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.UpdateRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.UpdateRequestBody();
            inValue.Body.command = command;
            return ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateResponse POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.ChangeActivityState(POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequest request) {
            return base.Channel.ChangeActivityState(request);
        }
        
        public POC.ServerASMX.Test.Tools.CustomerService.CommandResult ChangeActivityState(POC.ServerASMX.Test.Tools.CustomerService.CustomerActivityStateCommand command) {
            POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequestBody();
            inValue.Body.command = command;
            POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateResponse retVal = ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).ChangeActivityState(inValue);
            return retVal.Body.ChangeActivityStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateResponse> POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.ChangeActivityStateAsync(POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequest request) {
            return base.Channel.ChangeActivityStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateResponse> ChangeActivityStateAsync(POC.ServerASMX.Test.Tools.CustomerService.CustomerActivityStateCommand command) {
            POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.ChangeActivityStateRequestBody();
            inValue.Body.command = command;
            return ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).ChangeActivityStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POC.ServerASMX.Test.Tools.CustomerService.DeleteResponse POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.Delete(POC.ServerASMX.Test.Tools.CustomerService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public POC.ServerASMX.Test.Tools.CustomerService.CommandResult Delete(POC.ServerASMX.Test.Tools.CustomerService.CustomerDeleteCommand command) {
            POC.ServerASMX.Test.Tools.CustomerService.DeleteRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.DeleteRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.DeleteRequestBody();
            inValue.Body.command = command;
            POC.ServerASMX.Test.Tools.CustomerService.DeleteResponse retVal = ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.DeleteResponse> POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.DeleteAsync(POC.ServerASMX.Test.Tools.CustomerService.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.DeleteResponse> DeleteAsync(POC.ServerASMX.Test.Tools.CustomerService.CustomerDeleteCommand command) {
            POC.ServerASMX.Test.Tools.CustomerService.DeleteRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.DeleteRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.DeleteRequestBody();
            inValue.Body.command = command;
            return ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POC.ServerASMX.Test.Tools.CustomerService.GetResponse POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.Get(POC.ServerASMX.Test.Tools.CustomerService.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public POC.ServerASMX.Test.Tools.CustomerService.CustomerQueryResult Get(long id) {
            POC.ServerASMX.Test.Tools.CustomerService.GetRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.GetRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.GetRequestBody();
            inValue.Body.id = id;
            POC.ServerASMX.Test.Tools.CustomerService.GetResponse retVal = ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.GetResponse> POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.GetAsync(POC.ServerASMX.Test.Tools.CustomerService.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.GetResponse> GetAsync(long id) {
            POC.ServerASMX.Test.Tools.CustomerService.GetRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.GetRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.GetRequestBody();
            inValue.Body.id = id;
            return ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POC.ServerASMX.Test.Tools.CustomerService.ListResponse POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.List(POC.ServerASMX.Test.Tools.CustomerService.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public System.Collections.Generic.List<POC.ServerASMX.Test.Tools.CustomerService.CustomerQueryResult> List() {
            POC.ServerASMX.Test.Tools.CustomerService.ListRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.ListRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.ListRequestBody();
            POC.ServerASMX.Test.Tools.CustomerService.ListResponse retVal = ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).List(inValue);
            return retVal.Body.ListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.ListResponse> POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap.ListAsync(POC.ServerASMX.Test.Tools.CustomerService.ListRequest request) {
            return base.Channel.ListAsync(request);
        }
        
        public System.Threading.Tasks.Task<POC.ServerASMX.Test.Tools.CustomerService.ListResponse> ListAsync() {
            POC.ServerASMX.Test.Tools.CustomerService.ListRequest inValue = new POC.ServerASMX.Test.Tools.CustomerService.ListRequest();
            inValue.Body = new POC.ServerASMX.Test.Tools.CustomerService.ListRequestBody();
            return ((POC.ServerASMX.Test.Tools.CustomerService.CustomerServiceSoap)(this)).ListAsync(inValue);
        }
    }
}
