//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerASMX.Test.Base.CustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notifier", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.CustomerUpdateCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.CustomerActivityStateCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.CustomerDeleteCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.CustomerAddCommand))]
    public partial class Notifier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerUpdateCommand", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerUpdateCommand : ServerASMX.Test.Base.CustomerService.Notifier {
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime BirthField;
        
        private ServerASMX.Test.Base.CustomerService.EGender GenderField;
        
        private decimal CashBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Birth {
            get {
                return this.BirthField;
            }
            set {
                if ((this.BirthField.Equals(value) != true)) {
                    this.BirthField = value;
                    this.RaisePropertyChanged("Birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public ServerASMX.Test.Base.CustomerService.EGender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal CashBalance {
            get {
                return this.CashBalanceField;
            }
            set {
                if ((this.CashBalanceField.Equals(value) != true)) {
                    this.CashBalanceField = value;
                    this.RaisePropertyChanged("CashBalance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerActivityStateCommand", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerActivityStateCommand : ServerASMX.Test.Base.CustomerService.Notifier {
        
        private long IdField;
        
        private bool ActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDeleteCommand", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerDeleteCommand : ServerASMX.Test.Base.CustomerService.Notifier {
        
        private long IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerAddCommand", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerAddCommand : ServerASMX.Test.Base.CustomerService.Notifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime BirthField;
        
        private ServerASMX.Test.Base.CustomerService.EGender GenderField;
        
        private decimal CashBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Birth {
            get {
                return this.BirthField;
            }
            set {
                if ((this.BirthField.Equals(value) != true)) {
                    this.BirthField = value;
                    this.RaisePropertyChanged("Birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public ServerASMX.Test.Base.CustomerService.EGender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal CashBalance {
            get {
                return this.CashBalanceField;
            }
            set {
                if ((this.CashBalanceField.Equals(value) != true)) {
                    this.CashBalanceField = value;
                    this.RaisePropertyChanged("CashBalance");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EGender", Namespace="http://tempuri.org/")]
    public enum EGender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.CustomerAddCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.Notifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.EGender))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ServerASMX.Test.Base.CustomerService.Notification>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.Notification))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.CustomerCommandOutput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.CustomerUpdateCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.CustomerActivityStateCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.CustomerDeleteCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServerASMX.Test.Base.CustomerService.CustomerQueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ServerASMX.Test.Base.CustomerService.CustomerQueryResult>))]
    public partial class CommandResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ServerASMX.Test.Base.CustomerService.Notification> ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<ServerASMX.Test.Base.CustomerService.Notification> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Notification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Property {
            get {
                return this.PropertyField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyField, value) != true)) {
                    this.PropertyField = value;
                    this.RaisePropertyChanged("Property");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerCommandOutput", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerCommandOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime BirthField;
        
        private ServerASMX.Test.Base.CustomerService.EGender GenderField;
        
        private decimal CashBalanceField;
        
        private bool ActiveField;
        
        private System.DateTime CreationDateField;
        
        private System.Nullable<System.DateTime> ChangeDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Birth {
            get {
                return this.BirthField;
            }
            set {
                if ((this.BirthField.Equals(value) != true)) {
                    this.BirthField = value;
                    this.RaisePropertyChanged("Birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public ServerASMX.Test.Base.CustomerService.EGender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal CashBalance {
            get {
                return this.CashBalanceField;
            }
            set {
                if ((this.CashBalanceField.Equals(value) != true)) {
                    this.CashBalanceField = value;
                    this.RaisePropertyChanged("CashBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> ChangeDate {
            get {
                return this.ChangeDateField;
            }
            set {
                if ((this.ChangeDateField.Equals(value) != true)) {
                    this.ChangeDateField = value;
                    this.RaisePropertyChanged("ChangeDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerQueryResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerQueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime BirthField;
        
        private ServerASMX.Test.Base.CustomerService.EGender GenderField;
        
        private decimal CashBalanceField;
        
        private bool ActiveField;
        
        private System.DateTime CreationDateField;
        
        private System.Nullable<System.DateTime> ChangeDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Birth {
            get {
                return this.BirthField;
            }
            set {
                if ((this.BirthField.Equals(value) != true)) {
                    this.BirthField = value;
                    this.RaisePropertyChanged("Birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public ServerASMX.Test.Base.CustomerService.EGender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal CashBalance {
            get {
                return this.CashBalanceField;
            }
            set {
                if ((this.CashBalanceField.Equals(value) != true)) {
                    this.CashBalanceField = value;
                    this.RaisePropertyChanged("CashBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> ChangeDate {
            get {
                return this.ChangeDateField;
            }
            set {
                if ((this.ChangeDateField.Equals(value) != true)) {
                    this.ChangeDateField = value;
                    this.RaisePropertyChanged("ChangeDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.CustomerServiceSoap")]
    public interface CustomerServiceSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento command no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        ServerASMX.Test.Base.CustomerService.AddResponse Add(ServerASMX.Test.Base.CustomerService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.AddResponse> AddAsync(ServerASMX.Test.Base.CustomerService.AddRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento command no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        ServerASMX.Test.Base.CustomerService.UpdateResponse Update(ServerASMX.Test.Base.CustomerService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.UpdateResponse> UpdateAsync(ServerASMX.Test.Base.CustomerService.UpdateRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento command no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeActivityState", ReplyAction="*")]
        ServerASMX.Test.Base.CustomerService.ChangeActivityStateResponse ChangeActivityState(ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeActivityState", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.ChangeActivityStateResponse> ChangeActivityStateAsync(ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento command no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        ServerASMX.Test.Base.CustomerService.DeleteResponse Delete(ServerASMX.Test.Base.CustomerService.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.DeleteResponse> DeleteAsync(ServerASMX.Test.Base.CustomerService.DeleteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento GetResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        ServerASMX.Test.Base.CustomerService.GetResponse Get(ServerASMX.Test.Base.CustomerService.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.GetResponse> GetAsync(ServerASMX.Test.Base.CustomerService.GetRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento ListResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        ServerASMX.Test.Base.CustomerService.ListResponse List(ServerASMX.Test.Base.CustomerService.ListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.ListResponse> ListAsync(ServerASMX.Test.Base.CustomerService.ListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(ServerASMX.Test.Base.CustomerService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServerASMX.Test.Base.CustomerService.CustomerAddCommand command;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(ServerASMX.Test.Base.CustomerService.CustomerAddCommand command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(ServerASMX.Test.Base.CustomerService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServerASMX.Test.Base.CustomerService.CommandResult AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(ServerASMX.Test.Base.CustomerService.CommandResult AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(ServerASMX.Test.Base.CustomerService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServerASMX.Test.Base.CustomerService.CustomerUpdateCommand command;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(ServerASMX.Test.Base.CustomerService.CustomerUpdateCommand command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(ServerASMX.Test.Base.CustomerService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServerASMX.Test.Base.CustomerService.CommandResult UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(ServerASMX.Test.Base.CustomerService.CommandResult UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeActivityStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeActivityState", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequestBody Body;
        
        public ChangeActivityStateRequest() {
        }
        
        public ChangeActivityStateRequest(ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeActivityStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServerASMX.Test.Base.CustomerService.CustomerActivityStateCommand command;
        
        public ChangeActivityStateRequestBody() {
        }
        
        public ChangeActivityStateRequestBody(ServerASMX.Test.Base.CustomerService.CustomerActivityStateCommand command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeActivityStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeActivityStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.ChangeActivityStateResponseBody Body;
        
        public ChangeActivityStateResponse() {
        }
        
        public ChangeActivityStateResponse(ServerASMX.Test.Base.CustomerService.ChangeActivityStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeActivityStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServerASMX.Test.Base.CustomerService.CommandResult ChangeActivityStateResult;
        
        public ChangeActivityStateResponseBody() {
        }
        
        public ChangeActivityStateResponseBody(ServerASMX.Test.Base.CustomerService.CommandResult ChangeActivityStateResult) {
            this.ChangeActivityStateResult = ChangeActivityStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(ServerASMX.Test.Base.CustomerService.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServerASMX.Test.Base.CustomerService.CustomerDeleteCommand command;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(ServerASMX.Test.Base.CustomerService.CustomerDeleteCommand command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(ServerASMX.Test.Base.CustomerService.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServerASMX.Test.Base.CustomerService.CommandResult DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(ServerASMX.Test.Base.CustomerService.CommandResult DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(ServerASMX.Test.Base.CustomerService.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(ServerASMX.Test.Base.CustomerService.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServerASMX.Test.Base.CustomerService.CustomerQueryResult GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(ServerASMX.Test.Base.CustomerService.CustomerQueryResult GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="List", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.ListRequestBody Body;
        
        public ListRequest() {
        }
        
        public ListRequest(ServerASMX.Test.Base.CustomerService.ListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListRequestBody {
        
        public ListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServerASMX.Test.Base.CustomerService.ListResponseBody Body;
        
        public ListResponse() {
        }
        
        public ListResponse(ServerASMX.Test.Base.CustomerService.ListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServerASMX.Test.Base.CustomerService.CustomerQueryResult> ListResult;
        
        public ListResponseBody() {
        }
        
        public ListResponseBody(System.Collections.Generic.List<ServerASMX.Test.Base.CustomerService.CustomerQueryResult> ListResult) {
            this.ListResult = ListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceSoapChannel : ServerASMX.Test.Base.CustomerService.CustomerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceSoapClient : System.ServiceModel.ClientBase<ServerASMX.Test.Base.CustomerService.CustomerServiceSoap>, ServerASMX.Test.Base.CustomerService.CustomerServiceSoap {
        
        public CustomerServiceSoapClient() {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServerASMX.Test.Base.CustomerService.AddResponse ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.Add(ServerASMX.Test.Base.CustomerService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public ServerASMX.Test.Base.CustomerService.CommandResult Add(ServerASMX.Test.Base.CustomerService.CustomerAddCommand command) {
            ServerASMX.Test.Base.CustomerService.AddRequest inValue = new ServerASMX.Test.Base.CustomerService.AddRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.AddRequestBody();
            inValue.Body.command = command;
            ServerASMX.Test.Base.CustomerService.AddResponse retVal = ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.AddResponse> ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.AddAsync(ServerASMX.Test.Base.CustomerService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.AddResponse> AddAsync(ServerASMX.Test.Base.CustomerService.CustomerAddCommand command) {
            ServerASMX.Test.Base.CustomerService.AddRequest inValue = new ServerASMX.Test.Base.CustomerService.AddRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.AddRequestBody();
            inValue.Body.command = command;
            return ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServerASMX.Test.Base.CustomerService.UpdateResponse ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.Update(ServerASMX.Test.Base.CustomerService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public ServerASMX.Test.Base.CustomerService.CommandResult Update(ServerASMX.Test.Base.CustomerService.CustomerUpdateCommand command) {
            ServerASMX.Test.Base.CustomerService.UpdateRequest inValue = new ServerASMX.Test.Base.CustomerService.UpdateRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.UpdateRequestBody();
            inValue.Body.command = command;
            ServerASMX.Test.Base.CustomerService.UpdateResponse retVal = ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.UpdateResponse> ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.UpdateAsync(ServerASMX.Test.Base.CustomerService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.UpdateResponse> UpdateAsync(ServerASMX.Test.Base.CustomerService.CustomerUpdateCommand command) {
            ServerASMX.Test.Base.CustomerService.UpdateRequest inValue = new ServerASMX.Test.Base.CustomerService.UpdateRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.UpdateRequestBody();
            inValue.Body.command = command;
            return ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServerASMX.Test.Base.CustomerService.ChangeActivityStateResponse ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.ChangeActivityState(ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequest request) {
            return base.Channel.ChangeActivityState(request);
        }
        
        public ServerASMX.Test.Base.CustomerService.CommandResult ChangeActivityState(ServerASMX.Test.Base.CustomerService.CustomerActivityStateCommand command) {
            ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequest inValue = new ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequestBody();
            inValue.Body.command = command;
            ServerASMX.Test.Base.CustomerService.ChangeActivityStateResponse retVal = ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).ChangeActivityState(inValue);
            return retVal.Body.ChangeActivityStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.ChangeActivityStateResponse> ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.ChangeActivityStateAsync(ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequest request) {
            return base.Channel.ChangeActivityStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.ChangeActivityStateResponse> ChangeActivityStateAsync(ServerASMX.Test.Base.CustomerService.CustomerActivityStateCommand command) {
            ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequest inValue = new ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.ChangeActivityStateRequestBody();
            inValue.Body.command = command;
            return ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).ChangeActivityStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServerASMX.Test.Base.CustomerService.DeleteResponse ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.Delete(ServerASMX.Test.Base.CustomerService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public ServerASMX.Test.Base.CustomerService.CommandResult Delete(ServerASMX.Test.Base.CustomerService.CustomerDeleteCommand command) {
            ServerASMX.Test.Base.CustomerService.DeleteRequest inValue = new ServerASMX.Test.Base.CustomerService.DeleteRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.DeleteRequestBody();
            inValue.Body.command = command;
            ServerASMX.Test.Base.CustomerService.DeleteResponse retVal = ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.DeleteResponse> ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.DeleteAsync(ServerASMX.Test.Base.CustomerService.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.DeleteResponse> DeleteAsync(ServerASMX.Test.Base.CustomerService.CustomerDeleteCommand command) {
            ServerASMX.Test.Base.CustomerService.DeleteRequest inValue = new ServerASMX.Test.Base.CustomerService.DeleteRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.DeleteRequestBody();
            inValue.Body.command = command;
            return ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServerASMX.Test.Base.CustomerService.GetResponse ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.Get(ServerASMX.Test.Base.CustomerService.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public ServerASMX.Test.Base.CustomerService.CustomerQueryResult Get(long id) {
            ServerASMX.Test.Base.CustomerService.GetRequest inValue = new ServerASMX.Test.Base.CustomerService.GetRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.GetRequestBody();
            inValue.Body.id = id;
            ServerASMX.Test.Base.CustomerService.GetResponse retVal = ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.GetResponse> ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.GetAsync(ServerASMX.Test.Base.CustomerService.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.GetResponse> GetAsync(long id) {
            ServerASMX.Test.Base.CustomerService.GetRequest inValue = new ServerASMX.Test.Base.CustomerService.GetRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.GetRequestBody();
            inValue.Body.id = id;
            return ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServerASMX.Test.Base.CustomerService.ListResponse ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.List(ServerASMX.Test.Base.CustomerService.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public System.Collections.Generic.List<ServerASMX.Test.Base.CustomerService.CustomerQueryResult> List() {
            ServerASMX.Test.Base.CustomerService.ListRequest inValue = new ServerASMX.Test.Base.CustomerService.ListRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.ListRequestBody();
            ServerASMX.Test.Base.CustomerService.ListResponse retVal = ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).List(inValue);
            return retVal.Body.ListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.ListResponse> ServerASMX.Test.Base.CustomerService.CustomerServiceSoap.ListAsync(ServerASMX.Test.Base.CustomerService.ListRequest request) {
            return base.Channel.ListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServerASMX.Test.Base.CustomerService.ListResponse> ListAsync() {
            ServerASMX.Test.Base.CustomerService.ListRequest inValue = new ServerASMX.Test.Base.CustomerService.ListRequest();
            inValue.Body = new ServerASMX.Test.Base.CustomerService.ListRequestBody();
            return ((ServerASMX.Test.Base.CustomerService.CustomerServiceSoap)(this)).ListAsync(inValue);
        }
    }
}
